// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AMRent.Data.Contexts;

#nullable disable

namespace AMRent.Data.Migrations
{
    [DbContext(typeof(FullDatabaseContext))]
    [Migration("20231120145458_TranslatableSettingsSchema")]
    partial class TranslatableSettingsSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Key")
                        .IsUnique();

                    b.ToTable("GenericTranslation", (string)null);
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "CountryCode")
                        .IsUnique();

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "pt",
                            CountryCode = "pt",
                            Name = "Português"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CountryCode = "uk",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ArticleTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("YoutubeURL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("LanguageId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleMapsURL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MondayToFridayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SaturdayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("OfficeLocation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "OfficeLocationId");

                    b.HasIndex("OfficeLocationId");

                    b.ToTable("OfficeLocationTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("QuestionAndAnswer", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionAndAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LanguageId", "QuestionAndAnswerId");

                    b.HasIndex("QuestionAndAnswerId");

                    b.ToTable("QuestionAndAnswerTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("TeamMember", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TeamMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("TeamMemberTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TranslatableSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = 3
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TranslatableSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "TranslatableSettingId");

                    b.HasIndex("TranslatableSettingId");

                    b.ToTable("TranslatableSettingTranslation", (string)null);
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany("GenericTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ArticleTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.Article", "Article")
                        .WithMany("Translations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.OfficeLocation", "OfficeLocation")
                        .WithMany("Translations")
                        .HasForeignKey("OfficeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.QuestionAndAnswer", "QuestionAndAnswer")
                        .WithMany("Translations")
                        .HasForeignKey("QuestionAndAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("QuestionAndAnswer");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TeamMember", "TeamMember")
                        .WithMany("Translations")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TranslatableSetting", "TranslatableSetting")
                        .WithMany("Translations")
                        .HasForeignKey("TranslatableSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslatableSetting");
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Navigation("GenericTranslations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Article", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
