// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AMRent.Data.Contexts;

#nullable disable

namespace AMRent.Data.Migrations
{
    [DbContext(typeof(FullDatabaseContext))]
    [Migration("20231204171020_GenericTextTranslationSchema_UpdateSeedFullSite")]
    partial class GenericTextTranslationSchema_UpdateSeedFullSite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GenericText", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Menu.Home"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Menu.Passageiros"
                        },
                        new
                        {
                            Id = 3,
                            Key = "Menu.Comerciais"
                        },
                        new
                        {
                            Id = 4,
                            Key = "Menu.Renting"
                        },
                        new
                        {
                            Id = 5,
                            Key = "Menu.Ofertas"
                        },
                        new
                        {
                            Id = 6,
                            Key = "Menu.Blog"
                        },
                        new
                        {
                            Id = 7,
                            Key = "Menu.Contactos"
                        },
                        new
                        {
                            Id = 8,
                            Key = "Footer.Coluna1.Titulo"
                        },
                        new
                        {
                            Id = 9,
                            Key = "Footer.Coluna2.Titulo"
                        },
                        new
                        {
                            Id = 10,
                            Key = "Footer.Coluna3.Titulo"
                        },
                        new
                        {
                            Id = 11,
                            Key = "Footer.Coluna4.Titulo"
                        },
                        new
                        {
                            Id = 12,
                            Key = "Footer.RedesSociais.Titulo"
                        },
                        new
                        {
                            Id = 13,
                            Key = "Footer.SobreNos"
                        },
                        new
                        {
                            Id = 14,
                            Key = "Footer.NossaEquipa"
                        },
                        new
                        {
                            Id = 15,
                            Key = "Footer.GuiaDeAluguer"
                        },
                        new
                        {
                            Id = 16,
                            Key = "Footer.TermosECondicoes"
                        },
                        new
                        {
                            Id = 17,
                            Key = "Footer.PoliticaDePrivacidade"
                        },
                        new
                        {
                            Id = 18,
                            Key = "Footer.PerguntasERespostas"
                        },
                        new
                        {
                            Id = 19,
                            Key = "Footer.HorarioDeTrabalho"
                        },
                        new
                        {
                            Id = 20,
                            Key = "Footer.Balcoes"
                        },
                        new
                        {
                            Id = 21,
                            Key = "Footer.Queixas"
                        },
                        new
                        {
                            Id = 22,
                            Key = "Header.Registo"
                        },
                        new
                        {
                            Id = 23,
                            Key = "Header.Entrar"
                        },
                        new
                        {
                            Id = 24,
                            Key = "Home.Procura.Recolha"
                        },
                        new
                        {
                            Id = 25,
                            Key = "Home.Procura.Devolucao"
                        },
                        new
                        {
                            Id = 26,
                            Key = "Home.Procura.Botao"
                        },
                        new
                        {
                            Id = 27,
                            Key = "Home.Campanhas.Titulo"
                        },
                        new
                        {
                            Id = 28,
                            Key = "Home.Campanhas.Subtitulo"
                        },
                        new
                        {
                            Id = 29,
                            Key = "Home.Processo.Titulo"
                        },
                        new
                        {
                            Id = 30,
                            Key = "Home.Processo.Subtitulo"
                        },
                        new
                        {
                            Id = 31,
                            Key = "Home.Factos.Titulo"
                        },
                        new
                        {
                            Id = 32,
                            Key = "Home.Factos.Subtitulo"
                        },
                        new
                        {
                            Id = 33,
                            Key = "Home.MaisAlugados.Titulo"
                        },
                        new
                        {
                            Id = 34,
                            Key = "Home.MaisAlugados.Subtitulo"
                        },
                        new
                        {
                            Id = 35,
                            Key = "Home.RazoesParaAlugarConnosco.Titulo"
                        },
                        new
                        {
                            Id = 36,
                            Key = "Home.RazoesParaAlugarConnosco.Subtitulo"
                        },
                        new
                        {
                            Id = 37,
                            Key = "Home.Testemunhos.Titulo"
                        },
                        new
                        {
                            Id = 38,
                            Key = "Home.Testemunhos.Subtitulo"
                        },
                        new
                        {
                            Id = 39,
                            Key = "Pesquisa.Filtros.Categoria"
                        },
                        new
                        {
                            Id = 40,
                            Key = "Pesquisa.Filtros.Combustivel"
                        },
                        new
                        {
                            Id = 41,
                            Key = "Pesquisa.Filtros.Transmissao"
                        },
                        new
                        {
                            Id = 42,
                            Key = "Pesquisa.Filtros.Botao"
                        },
                        new
                        {
                            Id = 43,
                            Key = "Pesquisa.Filtros.LimparFiltros"
                        },
                        new
                        {
                            Id = 44,
                            Key = "Pesquisa.Segmento.Exemplo"
                        },
                        new
                        {
                            Id = 45,
                            Key = "Pesquisa.Segmento.Preco.Dia"
                        },
                        new
                        {
                            Id = 46,
                            Key = "Pesquisa.Segmento.Botao"
                        },
                        new
                        {
                            Id = 47,
                            Key = "Segmento.Detalhe.Sidebar.Titulo"
                        },
                        new
                        {
                            Id = 48,
                            Key = "Segmento.Detalhe.Sidebar.LocalRecolha"
                        },
                        new
                        {
                            Id = 49,
                            Key = "Segmento.Detalhe.Sidebar.LocalDevolucao"
                        },
                        new
                        {
                            Id = 50,
                            Key = "Segmento.Detalhe.Sidebar.DataRecolha"
                        },
                        new
                        {
                            Id = 51,
                            Key = "Segmento.Detalhe.Sidebar.DataDevolucao"
                        },
                        new
                        {
                            Id = 52,
                            Key = "Segmento.Detalhe.Sidebar.Botao"
                        },
                        new
                        {
                            Id = 53,
                            Key = "Segmento.Detalhe.Especificacao.Titulo"
                        },
                        new
                        {
                            Id = 54,
                            Key = "Segmento.Detalhe.Extras.Titulo"
                        },
                        new
                        {
                            Id = 55,
                            Key = "Segmento.Detalhe.Seguro.Titulo"
                        },
                        new
                        {
                            Id = 56,
                            Key = "Blog.Lista.Artigo.Botao"
                        },
                        new
                        {
                            Id = 57,
                            Key = "Contactos.Escritorios.Titulo"
                        },
                        new
                        {
                            Id = 58,
                            Key = "Contactos.Formulario.Titulo"
                        },
                        new
                        {
                            Id = 59,
                            Key = "Contactos.Formulario.Nome"
                        },
                        new
                        {
                            Id = 60,
                            Key = "Contactos.Formulario.Email"
                        },
                        new
                        {
                            Id = 61,
                            Key = "Contactos.Formulario.Telefone"
                        },
                        new
                        {
                            Id = 62,
                            Key = "Contactos.Formulario.Texto"
                        },
                        new
                        {
                            Id = 63,
                            Key = "Contactos.Formulario.Botao"
                        },
                        new
                        {
                            Id = 64,
                            Key = "PerguntasERespostas.Titulo"
                        },
                        new
                        {
                            Id = 65,
                            Key = "PerguntasERespostas.Subtitulo"
                        },
                        new
                        {
                            Id = 66,
                            Key = "Pesquisa.Titulo"
                        },
                        new
                        {
                            Id = 67,
                            Key = "Pesquisa.Filtros.Lugares"
                        });
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTextTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("GenericTextId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "GenericTextId");

                    b.HasIndex("GenericTextId");

                    b.ToTable("GenericTextTranslation", (string)null);

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 1,
                            Value = "Home"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 2,
                            Value = "Passageiros"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 3,
                            Value = "Comerciais"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 4,
                            Value = "Renting"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 5,
                            Value = "Ofertas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 6,
                            Value = "Blog"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 7,
                            Value = "Contactos"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 8,
                            Value = "Sobre nós"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 9,
                            Value = "Mais"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 10,
                            Value = "Ligações rápidas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 11,
                            Value = "Informação de contacto"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 12,
                            Value = "Conecte-se connosco"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 13,
                            Value = "Sobre nós"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 14,
                            Value = "A nossa equipa"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 15,
                            Value = "Guia de aluguer"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 16,
                            Value = "Termos e condições"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 17,
                            Value = "Política de privacidade"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 18,
                            Value = "Perguntas e respostas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 19,
                            Value = "Horário de trabalho"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 20,
                            Value = "Balcões"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 21,
                            Value = "Queixas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 22,
                            Value = "Registo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 23,
                            Value = "Entrar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 24,
                            Value = "Recolha"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 25,
                            Value = "Devolução"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 26,
                            Value = "Procurar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 27,
                            Value = "Campanhas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 28,
                            Value = "Campanhas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 29,
                            Value = "Processo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 30,
                            Value = "Processo.Subtítulo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 31,
                            Value = "Factos"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 32,
                            Value = "Factos.Subtítulo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 33,
                            Value = "Mais alugados"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 34,
                            Value = "MaisAlugados.Subtítulo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 35,
                            Value = "Razões para alugar connosco"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 36,
                            Value = "RazõesParaAlugarconnosco.Subtítulo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 37,
                            Value = "Testemunhos"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 38,
                            Value = "Testemunhos.Subtítulo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 39,
                            Value = "Segmento"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 40,
                            Value = "Combustível"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 41,
                            Value = "Transmissão"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 42,
                            Value = "Filtrar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 43,
                            Value = "Limpar filtros"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 44,
                            Value = "Exemplo"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 45,
                            Value = "Dia"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 46,
                            Value = "Alugar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 47,
                            Value = "Recolha e Devolução"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 48,
                            Value = "Local de recolha"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 49,
                            Value = "Local de devolução"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 50,
                            Value = "Data de recolha"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 51,
                            Value = "Data de devolucao"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 52,
                            Value = "Alugar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 53,
                            Value = "Especificações"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 54,
                            Value = "Extras"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 55,
                            Value = "Seguro"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 56,
                            Value = "Ler mais"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 57,
                            Value = "Escritórios"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 58,
                            Value = "Contacte-nos"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 59,
                            Value = "Nome"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 60,
                            Value = "Email"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 61,
                            Value = "Telefone"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 62,
                            Value = "Texto"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 63,
                            Value = "Enviar"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 64,
                            Value = "Perguntas e respostas"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 65,
                            Value = ""
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 66,
                            Value = "Pesquisa"
                        },
                        new
                        {
                            LanguageId = 1,
                            GenericTextId = 67,
                            Value = "Lugares"
                        });
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Code", "CountryCode")
                        .IsUnique();

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "pt",
                            CountryCode = "pt",
                            Name = "Português"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CountryCode = "uk",
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fr",
                            CountryCode = "fr",
                            Name = "Français"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogArticleCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogArticleCategoryId");

                    b.ToTable("BlogArticle", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("BlogArticleCategory", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategoryTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("BlogArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "BlogArticleCategoryId");

                    b.HasIndex("BlogArticleCategoryId");

                    b.ToTable("BlogArticleCategoryTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("BlogArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("YoutubeURL")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("LanguageId", "ArticleId");

                    b.HasIndex("BlogArticleId");

                    b.ToTable("BlogArticleTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("AppliesToBookingsMadeFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppliesToBookingsMadeUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("ValueUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campaign", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CampaignTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CarCategory", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategoryTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarCategoryId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("CarCategoryTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("CarFuel", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuelTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarFuelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarFuelId");

                    b.HasIndex("CarFuelId");

                    b.ToTable("CarFuelTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("CarGearbox", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearboxTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarGearboxId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarGearboxId");

                    b.HasIndex("CarGearboxId");

                    b.ToTable("CarGearboxTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CarFuelId")
                        .HasColumnType("int");

                    b.Property<int>("CarGearboxId")
                        .HasColumnType("int");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("RentCountIncrement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarCategoryId");

                    b.HasIndex("CarFuelId");

                    b.HasIndex("CarGearboxId");

                    b.ToTable("CarSegment", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegmentTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarSegmentId");

                    b.HasIndex("CarSegmentId");

                    b.ToTable("CarSegmentTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("MaximumValue")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.ToTable("Extra", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ExtraTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "ExtraId");

                    b.HasIndex("ExtraId");

                    b.ToTable("ExtraTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleMapsURL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MondayToFridayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SaturdayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("OfficeLocation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "OfficeLocationId");

                    b.HasIndex("OfficeLocationId");

                    b.ToTable("OfficeLocationTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.PickupReturnLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("TaxType")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxValue")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.ToTable("PickupReturnLocation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.PickupReturnLocationTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PickupReturnLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("LanguageId", "PickupReturnLocationId");

                    b.HasIndex("PickupReturnLocationId");

                    b.ToTable("PickupReturnLocationTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FontAwesomeIconCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Process", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FontAwesomeIconCode = ""
                        },
                        new
                        {
                            Id = 2,
                            FontAwesomeIconCode = ""
                        },
                        new
                        {
                            Id = 3,
                            FontAwesomeIconCode = ""
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ProcessTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "ProcessId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessTranslation", (string)null);

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 1,
                            Text = "",
                            Title = "Processo 1"
                        },
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 2,
                            Text = "",
                            Title = "Processo 2"
                        },
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 3,
                            Text = "",
                            Title = "Processo 3"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("QuestionAndAnswer", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionAndAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LanguageId", "QuestionAndAnswerId");

                    b.HasIndex("QuestionAndAnswerId");

                    b.ToTable("QuestionAndAnswerTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeasonCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SeasonCategoryId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SeasonCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeasonCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Verão"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inverno"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FontAwesomeIconCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SocialNetwork", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("TeamMember", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TeamMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("TeamMemberTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Testimonial", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TestimonialTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TestimonialId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("LanguageId", "TestimonialId");

                    b.HasIndex("TestimonialId");

                    b.ToTable("TestimonialTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TranslatableSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = 3
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TranslatableSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "TranslatableSettingId");

                    b.HasIndex("TranslatableSettingId");

                    b.ToTable("TranslatableSettingTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("AppliesToBookingsMadeFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppliesToBookingsMadeUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("ValueUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTextTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.GenericText", "GenericText")
                        .WithMany("Translations")
                        .HasForeignKey("GenericTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany("GenericTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericText");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticleCategory", "BlogArticleCategory")
                        .WithMany("BlogArticles")
                        .HasForeignKey("BlogArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticleCategory");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategoryTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticleCategory", "BlogArticleCategory")
                        .WithMany("Translations")
                        .HasForeignKey("BlogArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticleCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticle", "BlogArticle")
                        .WithMany("Translations")
                        .HasForeignKey("BlogArticleId");

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticle");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CampaignTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.Campaign", "Campaign")
                        .WithMany("Translations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategoryTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarCategory", "CarCategory")
                        .WithMany("Translations")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuelTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarFuel", "CarFuel")
                        .WithMany("Translations")
                        .HasForeignKey("CarFuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarFuel");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearboxTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarGearbox", "CarGearbox")
                        .WithMany("Translations")
                        .HasForeignKey("CarGearboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarGearbox");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarCategory", "CarCategory")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.CarFuel", "CarFuel")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarFuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.CarGearbox", "CarGearbox")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarGearboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCategory");

                    b.Navigation("CarFuel");

                    b.Navigation("CarGearbox");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegmentTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarSegment", "CarSegment")
                        .WithMany("Translations")
                        .HasForeignKey("CarSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarSegment");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ExtraTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.Extra", "Extra")
                        .WithMany("Translations")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extra");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.OfficeLocation", "OfficeLocation")
                        .WithMany("Translations")
                        .HasForeignKey("OfficeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.PickupReturnLocationTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.PickupReturnLocation", "PickupReturnLocation")
                        .WithMany("Translations")
                        .HasForeignKey("PickupReturnLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("PickupReturnLocation");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ProcessTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.Process", "Process")
                        .WithMany("Translations")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.QuestionAndAnswer", "QuestionAndAnswer")
                        .WithMany("Translations")
                        .HasForeignKey("QuestionAndAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("QuestionAndAnswer");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Season", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.SeasonCategory", "SeasonCategory")
                        .WithMany("Season")
                        .HasForeignKey("SeasonCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonCategory");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TeamMember", "TeamMember")
                        .WithMany("Translations")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TestimonialTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.Testimonial", "Testimonial")
                        .WithMany("Translations")
                        .HasForeignKey("TestimonialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Testimonial");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TranslatableSetting", "TranslatableSetting")
                        .WithMany("Translations")
                        .HasForeignKey("TranslatableSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslatableSetting");
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericText", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Navigation("GenericTranslations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategory", b =>
                {
                    b.Navigation("BlogArticles");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Campaign", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategory", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuel", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearbox", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Extra", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.PickupReturnLocation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Process", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SeasonCategory", b =>
                {
                    b.Navigation("Season");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Testimonial", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
