// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AMRent.Data.Contexts;

#nullable disable

namespace AMRent.Data.Migrations
{
    [DbContext(typeof(FullDatabaseContext))]
    [Migration("20231126172218_UpdateSeasonAndSeasonCategoriesSchema_DatesUTC")]
    partial class UpdateSeasonAndSeasonCategoriesSchema_DatesUTC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Key")
                        .IsUnique();

                    b.ToTable("GenericTranslation", (string)null);
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Code", "CountryCode")
                        .IsUnique();

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "pt",
                            CountryCode = "pt",
                            Name = "Português"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            CountryCode = "uk",
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fr",
                            CountryCode = "fr",
                            Name = "Français"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogArticleCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogArticleCategoryId");

                    b.ToTable("BlogArticle", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("BlogArticleCategory", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategoryTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("BlogArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "BlogArticleCategoryId");

                    b.HasIndex("BlogArticleCategoryId");

                    b.ToTable("BlogArticleCategoryTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("BlogArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("YoutubeURL")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("LanguageId", "ArticleId");

                    b.HasIndex("BlogArticleId");

                    b.ToTable("BlogArticleTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("AppliesToBookingsMadeFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AppliesToBookingsMadeUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("ValueUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campaign", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CampaignTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("CarCategory", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategoryTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarCategoryId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("CarCategoryTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("CarFuel", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuelTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarFuelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarFuelId");

                    b.HasIndex("CarFuelId");

                    b.ToTable("CarFuelTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("CarGearbox", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearboxTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarGearboxId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarGearboxId");

                    b.HasIndex("CarGearboxId");

                    b.ToTable("CarGearboxTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CarFuelId")
                        .HasColumnType("int");

                    b.Property<int>("CarGearboxId")
                        .HasColumnType("int");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("RentCountIncrement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarCategoryId");

                    b.HasIndex("CarFuelId");

                    b.HasIndex("CarGearboxId");

                    b.ToTable("CarSegment", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegmentTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("CarSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "CarSegmentId");

                    b.HasIndex("CarSegmentId");

                    b.ToTable("CarSegmentTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleMapsURL")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MondayToFridayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SaturdayTimetable")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("OfficeLocation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("OfficeLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LanguageId", "OfficeLocationId");

                    b.HasIndex("OfficeLocationId");

                    b.ToTable("OfficeLocationTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FontAwesomeIconCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Process", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FontAwesomeIconCode = ""
                        },
                        new
                        {
                            Id = 2,
                            FontAwesomeIconCode = ""
                        },
                        new
                        {
                            Id = 3,
                            FontAwesomeIconCode = ""
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ProcessTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "ProcessId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessTranslation", (string)null);

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 1,
                            Text = "",
                            Title = "Processo 1"
                        },
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 2,
                            Text = "",
                            Title = "Processo 2"
                        },
                        new
                        {
                            LanguageId = 1,
                            ProcessId = 3,
                            Text = "",
                            Title = "Processo 3"
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("QuestionAndAnswer", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionAndAnswerId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LanguageId", "QuestionAndAnswerId");

                    b.HasIndex("QuestionAndAnswerId");

                    b.ToTable("QuestionAndAnswerTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SeasonCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SeasonCategoryId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SeasonCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeasonCategory", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FontAwesomeIconCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SocialNetwork", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("TeamMember", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TeamMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LanguageId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("TeamMemberTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Testimonial", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TestimonialTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TestimonialId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("LanguageId", "TestimonialId");

                    b.HasIndex("TestimonialId");

                    b.ToTable("TestimonialTranslation", (string)null);
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TranslatableSetting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = 3
                        });
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TranslatableSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "TranslatableSettingId");

                    b.HasIndex("TranslatableSettingId");

                    b.ToTable("TranslatableSettingTranslation", (string)null);
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.GenericTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany("GenericTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticleCategory", "BlogArticleCategory")
                        .WithMany("BlogArticles")
                        .HasForeignKey("BlogArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticleCategory");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategoryTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticleCategory", "BlogArticleCategory")
                        .WithMany("Translations")
                        .HasForeignKey("BlogArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticleCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.BlogArticle", "BlogArticle")
                        .WithMany("Translations")
                        .HasForeignKey("BlogArticleId");

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogArticle");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CampaignTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.Campaign", "Campaign")
                        .WithMany("Translations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategoryTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarCategory", "CarCategory")
                        .WithMany("Translations")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuelTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarFuel", "CarFuel")
                        .WithMany("Translations")
                        .HasForeignKey("CarFuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarFuel");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearboxTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarGearbox", "CarGearbox")
                        .WithMany("Translations")
                        .HasForeignKey("CarGearboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarGearbox");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarCategory", "CarCategory")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.CarFuel", "CarFuel")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarFuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.CarGearbox", "CarGearbox")
                        .WithMany("CarSegments")
                        .HasForeignKey("CarGearboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCategory");

                    b.Navigation("CarFuel");

                    b.Navigation("CarGearbox");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegmentTranslation", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.CarSegment", "CarSegment")
                        .WithMany("Translations")
                        .HasForeignKey("CarSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarSegment");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocationTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.OfficeLocation", "OfficeLocation")
                        .WithMany("Translations")
                        .HasForeignKey("OfficeLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.ProcessTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.Process", "Process")
                        .WithMany("Translations")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswerTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.QuestionAndAnswer", "QuestionAndAnswer")
                        .WithMany("Translations")
                        .HasForeignKey("QuestionAndAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("QuestionAndAnswer");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Season", b =>
                {
                    b.HasOne("AMRent.Data.Models.Database.SeasonCategory", "SeasonCategory")
                        .WithMany("Season")
                        .HasForeignKey("SeasonCategoryId");

                    b.Navigation("SeasonCategory");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMemberTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TeamMember", "TeamMember")
                        .WithMany("Translations")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TestimonialTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.Testimonial", "Testimonial")
                        .WithMany("Translations")
                        .HasForeignKey("TestimonialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Testimonial");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSettingTranslation", b =>
                {
                    b.HasOne("dCore.MultiLanguage.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMRent.Data.Models.Database.TranslatableSetting", "TranslatableSetting")
                        .WithMany("Translations")
                        .HasForeignKey("TranslatableSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslatableSetting");
                });

            modelBuilder.Entity("dCore.MultiLanguage.Models.Language", b =>
                {
                    b.Navigation("GenericTranslations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticle", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.BlogArticleCategory", b =>
                {
                    b.Navigation("BlogArticles");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Campaign", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarCategory", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarFuel", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarGearbox", b =>
                {
                    b.Navigation("CarSegments");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.CarSegment", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.OfficeLocation", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Process", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.QuestionAndAnswer", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.SeasonCategory", b =>
                {
                    b.Navigation("Season");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TeamMember", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.Testimonial", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AMRent.Data.Models.Database.TranslatableSetting", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
